# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currrent_stock', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('supplier', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
