# Generated by Django 2.0.7 on 2018-07-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=30)),
                ('prodct_price', models.IntegerField()),
                ('currrent_stock', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('supplier', models.CharField(blank='True', max_length=30)),
                ('quantity', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
