# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_code', models.IntegerField()),
                ('product_name', models.CharField(blank='True', max_length=30)),
                ('product_price', models.IntegerField()),
                ('currrent_stock', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('supplier', models.CharField(blank='True', max_length=30)),
                ('quantity', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
