# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockreturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('bill_no', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=30)),
                ('supplier_contact', models.CharField(max_length=30)),
            ],
        ),
    ]
