# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockreturn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreturn',
            name='supplier_contact',
            field=models.IntegerField(),
        ),
    ]
