# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockreturn', '0002_auto_20180712_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockreturn',
            name='supplier_name',
        ),
        migrations.AlterField(
            model_name='stockreturn',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
        migrations.AlterField(
            model_name='stockreturn',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
    ]
