# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-02 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100, unique=True)),
                ('prod_code', models.IntegerField(unique=True)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=17)),
                ('prod_category', models.CharField(max_length=100)),
                ('prod_description', models.TextField(max_length=500)),
                ('prod_quantity', models.IntegerField()),
                ('prod_discount', models.DecimalField(decimal_places=2, max_digits=17)),
                ('prod_tax', models.DecimalField(decimal_places=2, max_digits=17)),
                ('prod_cost', models.DecimalField(decimal_places=2, max_digits=17)),
            ],
        ),
    ]
