# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='product name')),
                ('prod_code', models.IntegerField(blank=True, unique=True, verbose_name='product code')),
                ('prod_price', models.DecimalField(blank=True, decimal_places=2, max_digits=17, verbose_name='product price')),
                ('prod_category', models.CharField(blank=True, max_length=100, verbose_name='product category')),
                ('prod_description', models.TextField(blank=True, max_length=500, verbose_name='product description')),
                ('prod_quantity', models.IntegerField(blank=True, verbose_name='product quantity')),
                ('prod_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=17, verbose_name='product discount')),
                ('prod_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=17, verbose_name='product tax')),
                ('prod_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=17, verbose_name='product cost')),
            ],
        ),
    ]
